package com.arklight.app

import android.os.Bundle
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.appcompat.app.AppCompatActivity
import androidx.core.splashscreen.SplashScreen.Companion.installSplashScreen
import androidx.core.view.WindowCompat
import androidx.webkit.WebViewAssetLoader

/**
 * Application-mode runtime shell, generated by `arklight android
 * scaffold` (see docs/Backends/ANDROID-BACKEND-IMPLEMENTATION.md,
 * Stage 1). Unlike ARKlight-Viewer-for-Android-Devices's own
 * MainActivity, this build has exactly one fixed site baked into
 * `assets/` at generation time -- no bundle picker, no menu, no
 * passphrase prompt. Every visible element that exists only because
 * that app used to be a browser for arbitrary `.ark` bundles is left
 * out here, per this milestone's "if a visible element exists solely
 * because the app used to be a browser for arbitrary bundles, it
 * doesn't belong in application mode" rule.
 *
 * Origin strategy carries over unchanged from the Viewer runtime this
 * evolved from: `androidx.webkit.WebViewAssetLoader` serves this
 * app's `assets/` folder under the same stable
 * `https://appassets.androidplatform.net` origin a plain `file://`
 * load can't provide, which is what makes ARKlight's
 * `State(persist=True)` -> `localStorage` reliable here.
 *
 * `ArkBundle.kt`/`ArkSeal.kt`/`MemoryGuard.kt` ship alongside this
 * file (vendored unchanged from the Viewer app) but go unused by this
 * default, unpacked-tree code path -- see
 * ANDROID-BACKEND-IMPLEMENTATION.md's "Open questions for Stage 0",
 * "Packed .ark vs. unpacked tree": they're what a future sealed-
 * bundle Application-mode option would call into, without needing to
 * regenerate this project.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView

    override fun onCreate(savedInstanceState: Bundle?) {
        // Must be called before super.onCreate() -- swaps
        // Theme.ArkApp.Starting (set on this activity in the
        // manifest) for its postSplashScreenTheme (Theme.ArkApp) once
        // the splash screen is dismissed.
        installSplashScreen()
        super.onCreate(savedInstanceState)
        webView = WebView(this)
        setContentView(webView)

        webView.settings.javaScriptEnabled = true
        webView.settings.domStorageEnabled = true

        val assetLoader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .build()

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(
                view: WebView,
                request: WebResourceRequest
            ): WebResourceResponse? = assetLoader.shouldInterceptRequest(request.url)
        }

        webView.loadUrl(SITE_URL)
    }

    @Suppress("DEPRECATION")
    override fun onBackPressed() {
        if (webView.canGoBack()) webView.goBack() else super.onBackPressed()
    }

    companion object {
        private const val SITE_URL = "https://appassets.androidplatform.net/assets/index.html"
    }
}
