package com.arklight.rae_ark_web_novelist

import android.content.ActivityNotFoundException
import android.content.Intent
import android.content.pm.ApplicationInfo
import android.net.Uri
import android.os.Bundle
import android.webkit.WebResourceError
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.activity.OnBackPressedCallback
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.WindowCompat
import androidx.webkit.WebViewAssetLoader

/**
 * Application-mode runtime shell, generated by `arklight android
 * scaffold` (see docs/Backends/ANDROID-BACKEND-IMPLEMENTATION.md,
 * Stage 1). Unlike ARKlight-Viewer-for-Android-Devices's own
 * MainActivity, this build has exactly one fixed site baked into
 * `assets/` at generation time -- no bundle picker, no menu, no
 * passphrase prompt. Every visible element that exists only because
 * that app used to be a browser for arbitrary `.ark` bundles is left
 * out here, per this milestone's "if a visible element exists solely
 * because the app used to be a browser for arbitrary bundles, it
 * doesn't belong in application mode" rule.
 *
 * Origin strategy carries over unchanged from the Viewer runtime this
 * evolved from: `androidx.webkit.WebViewAssetLoader` serves this
 * app's `assets/` folder under the same stable
 * `https://appassets.androidplatform.net` origin a plain `file://`
 * load can't provide, which is what makes ARKlight's
 * `State(persist=True)` -> `localStorage` reliable here.
 *
 * Native-shell behavior (docs/Proposals/ANDROID-BACKEND-HARDENING-
 * PROPOSAL.md; none of it involves a JS-to-native bridge):
 *
 * - Links: a main-frame navigation to this app's own origin, or to a
 *   host listed in `android.allow_navigation`, loads in the WebView.
 *   Any other http(s) link, and mailto:/tel:/sms: links, are handed to
 *   whatever app on the device handles them. Nothing else about the
 *   WebView's link handling is changed.
 * - Back: the system back gesture (including Android 13+ predictive
 *   back) goes back through the WebView's history while it has any,
 *   and is otherwise left to the system.
 * - Rotation: the WebView's history and scroll position are saved and
 *   restored across activity recreation. In-page JavaScript state is
 *   not part of that -- only `State(persist=True)` survives a reload.
 * - Load errors: a failed main-frame load shows a plain built-in page
 *   instead of Chromium's own error page.
 * - WebView remote debugging (chrome://inspect) is on in debuggable
 *   builds only.
 *
 * `ArkBundle.kt`/`ArkSeal.kt`/`MemoryGuard.kt` ship alongside this
 * file (vendored unchanged from the Viewer app) but go unused by this
 * default, unpacked-tree code path -- see
 * ANDROID-BACKEND-IMPLEMENTATION.md's "Open questions for Stage 0",
 * "Packed .ark vs. unpacked tree": they're what a future sealed-
 * bundle Application-mode option would call into, without needing to
 * regenerate this project.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView

    // Enabled only while the WebView has history to go back through.
    // When disabled the system handles back itself, which is what lets
    // predictive back show its back-to-home animation instead of the
    // app swallowing the gesture.
    private val backCallback = object : OnBackPressedCallback(false) {
        override fun handleOnBackPressed() {
            if (webView.canGoBack()) webView.goBack()
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        webView = WebView(this)
        setContentView(webView)

        webView.settings.javaScriptEnabled = true
        webView.settings.domStorageEnabled = true

        // Tied to the build type rather than a config key: a debuggable
        // (debug) build can be inspected, a release build never can.
        WebView.setWebContentsDebuggingEnabled(
            (applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE) != 0
        )

        val assetLoader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .build()

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(
                view: WebView,
                request: WebResourceRequest
            ): WebResourceResponse? = assetLoader.shouldInterceptRequest(request.url)

            override fun shouldOverrideUrlLoading(
                view: WebView,
                request: WebResourceRequest
            ): Boolean = request.isForMainFrame && routeNavigation(request.url)

            override fun onReceivedError(
                view: WebView,
                request: WebResourceRequest,
                error: WebResourceError
            ) {
                if (request.isForMainFrame) {
                    view.loadDataWithBaseURL(
                        null, LOAD_ERROR_HTML, "text/html", "UTF-8", request.url.toString()
                    )
                }
            }

            override fun doUpdateVisitedHistory(view: WebView, url: String?, isReload: Boolean) {
                backCallback.isEnabled = view.canGoBack()
            }
        }

        onBackPressedDispatcher.addCallback(this, backCallback)

        // A saved state that can't be restored (null) falls through to
        // a normal first load rather than leaving a blank WebView.
        if (savedInstanceState == null || webView.restoreState(savedInstanceState) == null) {
            webView.loadUrl(SITE_URL)
        }
        backCallback.isEnabled = webView.canGoBack()
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        webView.saveState(outState)
    }

    /**
     * Decides who loads a main-frame navigation. Returns true when it
     * was dealt with here (handed to another app), so the WebView must
     * not also load it; false to let the WebView load it as usual.
     */
    private fun routeNavigation(uri: Uri): Boolean {
        if (isInApp(uri)) return false
        val scheme = uri.scheme?.lowercase() ?: return false
        if (scheme !in EXTERNAL_SCHEMES) return false
        try {
            startActivity(Intent(Intent.ACTION_VIEW, uri))
        } catch (e: ActivityNotFoundException) {
            // Nothing on this device handles that link; stay on the page.
        }
        return true
    }

    /** This app's own origin, or an https host `allow_navigation` names. */
    private fun isInApp(uri: Uri): Boolean {
        if (uri.scheme?.lowercase() != "https") return false
        val host = uri.host?.lowercase() ?: return false
        if (host == ASSET_HOST) return true
        return ALLOWED_HOSTS.any { pattern ->
            if (pattern.startsWith("*.")) host.endsWith(pattern.substring(1)) else host == pattern
        }
    }

    companion object {
        private const val SITE_URL = "https://appassets.androidplatform.net/assets/index.html"
        private const val ASSET_HOST = "appassets.androidplatform.net"

        // From `android.allow_navigation` in arklight.config.py. A
        // leading "*." matches subdomains only, not the bare domain.
        private val ALLOWED_HOSTS: List<String> = emptyList()

        private val EXTERNAL_SCHEMES = setOf("http", "https", "mailto", "tel", "sms")

        // Static on purpose: nothing from the failed URL is interpolated.
        private const val LOAD_ERROR_HTML =
            "<!doctype html><html><head><meta charset='utf-8'>" +
            "<meta name='viewport' content='width=device-width,initial-scale=1'>" +
            "<meta name='color-scheme' content='light dark'>" +
            "<title>Page unavailable</title></head>" +
            "<body style='font-family:sans-serif;margin:2rem;line-height:1.5'>" +
            "<h1 style='font-size:1.25rem'>This page couldn't be loaded</h1>" +
            "<p>Check your connection, then go back and try again.</p>" +
            "</body></html>"
    }
}
